spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/calokilo
        username: calokilo-pg
        password: verySecretPassword

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
