server:
    port: 8080

spring:
    application:
        name: user-service

    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}

    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    activemq:
        broker-url: ${SPRING_JMS_URL}
        user: ${SPRING_JMS_USERNAME}
        password: ${SPRING_JMS_PASSWORD}

eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka/