server:
    port: 8081

spring:
    application:
        name: weight-service

    data:
        mongodb:
            host: localhost
            port: 27017
            database: calokilo
            username: root
            password: verySecretPassword
            authentication-database: admin

    activemq:
        broker-url: tcp://localhost:61616
        user: calokilo
        password: veryStrongPassword

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/