server:
    port: 8081

spring:
    application:
        name: weight-service

    data:
        mongodb:
            host: ${SPRING_DATASOURCE_HOST}
            port: ${SPRING_DATASOURCE_PORT}
            database: ${SPRING_DATASOURCE_DB}
            username: ${SPRING_DATASOURCE_USERNAME}
            password: ${SPRING_DATASOURCE_PASSWORD}
            authentication-database: admin

    activemq:
        broker-url: ${SPRING_JMS_URL}
        user: ${SPRING_JMS_USERNAME}
        password: ${SPRING_JMS_PASSWORD}

eureka:
    client:
        serviceUrl:
            defaultZone: http://discovery-server:8761/eureka/