eureka:
    instance:
        hostname: localhost

    client:
        registerWithEureka: false # as a server, we don't want to register as a service with eureka
        fetchRegistry: false # as a server, we already maintain a local registry

server:
    port: 8761